config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #root 'posts#index'
  resources :users
  resources :comments
  resources :posts do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  attr_accessor :username, :body, :mark, :post_id
  validates :username, :body, :mark, :post_id, presence: true
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    belongs_to :user
    validates :title, presence: true, length: {minimum: 5}
    
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    has_many :posts
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    layout false
    skip_before_action :verify_authenticity_token
    
    def index
        @comment = Post.find(params[:post_id]).comments.find_all
        pp @comment
        if @comments = Comment.where(post_id: params[:post_id])
            render json: {comments: @comments}, status: 200
        end
    end

    def create
        @json_data = JSON.parse(request.raw_post)
        pp '1!!!!'
        pp @json_data
        pp '1!!!!'
        pp params[:username]
        @c = Comment.new(@json_data)
        pp @c
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(@json_data)
        pp @comment
        @comment.user_id = User.find_by(name: params[:username]).id
        if @comment.save
            render json: @comment
        else
            render json: @comment.errors
        end
    end

    def destroy
        @comment = Comment.find(params[:id])
        if @comment.destroy()
            render json: {}, status: 200
        else
            render json: {}, status: 500
        end
    end

    def show
        @comment = Post.find(params[:post_id]).comments.find(params[:id])
    end

    private def comment_params
        params.require(:comment).permit(:username, :body, :mark)
        #params.permit(:username, :body, :mark)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    #http_basic_authenticate_with name:"admin", password: "123", except: [:index, :show]
    layout false
    skip_before_action :verify_authenticity_token
    def index
        @post = Post.all
        render json: {posts: @post}, status: 200
    end

    def new
        @post = Post.new
    end

    def destroy
        @post = Post.find(params[:id])
        @user = User.find(@post.user_id)
        @countOfPosts = @user.countOfPosts
        @countOfPosts -= 1
        if @post.destroy() && @user.update(countOfPosts: @countOfPosts)
          render json: {}, status: 200
        else
          render json: {}, status: 500
        end

    end

    def update
        @json_data = JSON.parse(request.raw_post)
        @post = Post.find(params[:id])
        if @post.update(@json_data)
            render json: @post
        else
            render json: @post.errors
        end
    end

    def edit
        @post = Post.find(params[:id])
      end

    def show
        @post = Post.find(params[:id])
    end

    def create
        @json_data = JSON.parse(request.raw_post)
        @post = Post.new(@json_data)
        @user = User.find(@post.user_id)
        @countOfPosts = @user.countOfPosts
        @countOfPosts += 1

        if @post.save && @user.update(countOfPosts: @countOfPosts)
            render json: @post
        else
            render body: @post.errors
        end
    end

    private def post_params
        params.require(:post).permit(:title, :body)
      end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
  
    def create
      user = User.find_by(name: params[:session][:name].downcase)
      if user
          sign_in user
          redirect_to user
      else
      flash.now[:error] = "Invalid email/password combination"
      render 'new'
    end
  
    def destroy
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # before_create :create_remember_token
    layout false
    skip_before_action :verify_authenticity_token
    def index
        if params['regBef'] # do
            tmp = DateTime.parse(params['regBef'])
            @user = User.where("created_at <= ?", tmp)

        else
            if params['regAft'] # posle
                tmp = DateTime.parse(params['regAft'])
                @user = User.where("created_at > ?", tmp)
            else
                @user = User.all
            end
        end
        render json: {users: @user}, status: 200
    end

    def new
        @user = User.new
    end

    def show
        @user = User.find(params[:id])
        @posts = @user.posts
        @comments = @user.comments
        render json: {users: @user, articles: @posts, comments: @comments}, status: 200
      
    end
    
    def destroy
        @user = User.find(params[:id])
        "if @user.countOfPosts > 0
            @posts = Post.where(user_id: @user.id)
            @posts.destroy_all
        end"
        if @user.countOfPosts == 0 && @user.destroy
            render json: {}, status: 200
        else
            render json: {error: 'this user has posts.'}, status: 500
        end
    end

    def update
        @json_data = JSON.parse(request.raw_post)
        @user = User.find(params[:id])
        if @user.update(@json_data)
            render json: @user
        else
            render json: @user.errors
        end
    end


    def create
        @json_data = JSON.parse(request.raw_post)
        @user = User.new(@json_data)
        @user.countOfPosts = 0
        if @user.save
            render json: @user
        else
            render json: @user.errors
        end
    end
    
    private def user_params
        params.permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in(user)
        remember_token = User.encrypt(cookies[:remember_token])
        cookies.permanent[:remember_token] = remember_token
        user.update_attribute(:remember_token, User.encrypt(remember_token))
        self.current_user = user                        
    end

    def signed_in?
        !current_user.nil?
    end

    def current_user=(user)
        @current_user = user
    end

    def current_user
        @current_user ||= User.find_by(remember_token: remember_token)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"%>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h2>edit post</h2>

<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %> </div>
        <% end %>
    <% end %>
    <p>
        Название<br>
        <%= f.text_field(:title) %>
    </p>
    
    <p>
        Текст статьи<br>
        <%= f.text_area(:body) %>
    </p>
    
    <p>
        <%= f.submit ({:class => 'btn btn-success'}) %>
    </p>

<% end %>

app/views/posts/index.html.erb
<h1>All</h1>
<% @post.each do |post| %>
    <div>
        <h3><%= post.title %></h3>
        <p><%= post.body %></p>
        <%= link_to "read", post_path(post), :class => 'btn btn-warning' %>
    </div>
<% end %>

app/views/posts/new.html.erb
<h2>new post</h2>

<%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %> </div>
        <% end %>
    <% end %>

    <p>
        Название<br>
        <%= f.text_field :title %>
    </p>
    
    <p>
        Текст статьи<br>
        <%= f.text_area :body %>
    </p>
    <p>
        <%= f.submit %>
    </p>

<% end %>

app/views/posts/show.html.erb
<h3>Название: <%= @post.title%></h3>
<p>Текст: <%= @post.body%></p>
<hr>
<%= link_to "Редактировать", edit_post_path(@post), :class => 'btn' %>
<%= button_to "Удалить", post_path(@post), method: :delete, :class => 'btn btn-warning' %>
<hr>
<h2>Все комментарии</h2>
<% @post.comments.each do |comment| %>
    <div>
        <p><strong><%= comment.username%> </strong>: <%= comment.body%></p>
    </div>
<% end %>
<hr>
<h2>Добавление Комментария</h2>
<%= form_for ([@post, @post.comments.build]) do |f| %>
    <p>
        Пользователь<br>
        <%= f.text_field :username %>
    </p>
    
    <p>
        Текст комментария<br>
        <%= f.text_area :body %>
    </p>
    
    <p>
        <%= f.submit("Добавить комментарий") %>
    </p>

<% end %>

app/views/users/index.html.erb
<h1>All</h1>
<% @user.each do |user| %>
    <div>
        <h3><%= user.name %></h3>
        <%= link_to "read", user_path(user), :class => 'btn btn-warning' %>
    </div>
<% end %>

app/views/users/new.html.erb
<h2>new user</h2>

<%= form_for :user, url: users_path do |f| %>
    <% if @user.errors.any? %>
        <% @user.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %> </div>
        <% end %>
    <% end %>
    <p>
        UserName<br>
        <%= f.text_field :name %>
    </p>
    

    <p>
        <%= f.submit %>
    </p>

<% end %>

app/views/users/show.html.erb
<h3>Название: <%= @user.name%></h3>

<hr>

<%= button_to "Удалить", user_path(@user), method: :delete, :class => 'btn btn-warning' %>
<hr>